default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  adapter: postgresql
  encoding: unicode
  url: <%=Rails.application.credentials.dev_db! %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

test:
  adapter: postgresql
  encoding: unicode
  url: <%=Rails.application.credentials.dev_db! %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>


production:
  adapter: postgresql
  encoding: unicode
  url: <%=Rails.application.credentials.prod_db! %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
