name: Rails Unit Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Build and test with Rake
      env:
        RAILS_ENV: development
      run: |
        sudo apt-get -yqq install libpq-dev
        touch config/master.key
        printf "${{secrets.RAILS_MASTER_KEY}}" > config/master.key
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails test

          
